### ISSUE TITLE
Add ASPNETCore.gitignore

### ISSUE THREAD

**Issue by doggy8088** [Arasz/dotnet-ignore#10]
In http://gitignore.io/ site, there is `ASPNETCore` template. Can you add this to your tool?

![image](https://user-images.githubusercontent.com/88981/82736379-e81cae80-9d5b-11ea-8466-0d4f0fb58219.png)

**Comment by lkurzyniec** [comment]
@doggy8088 this tool just listing files from https://github.com/github/gitignore repo. Someone has to add such template there to have it here ;)

**Comment by lkurzyniec** [comment]
@doggy8088 if you need .gitignore for .NET Core app then use visualstudio template (https://github.com/github/gitignore/blob/master/VisualStudio.gitignore), it's newer version of your ASPNETCore template.
