### ISSUE TITLE
Support merging multiple files

### ISSUE THREAD

**Issue by asherber** [Arasz/dotnet-ignore#5]
It would be great if this tool supported merging multiple .gitignore files. For example, I'm working on a project using VSCode and node.js. At gitignore.io, I can do https://gitignore.io/api/node,code to get a merged file with the correct ignores for VSCode and node.

**Comment by Arasz** [comment]
#7

**Comment by Arasz** [comment]
@asherber I added support for the merge of multiple files. The format is the same as at gitignore.io - file names can be listed using the comma as separator.  
For now, it's only a simple merge but more complicated strategy can be added in the future :)
