### ISSUE TITLE
Support .NET Core 3

### ISSUE THREAD

**Issue by ctyar** [Arasz/dotnet-ignore#6]
Right now the project only works with .NET Core 2.2.
It would be nice to add support for 3.0 and 2.1 (as it is LTS).

I can send a PR if it's ok with you.

**Comment by Arasz** [comment]
Sure, PR is welcome so go ahead 👍

**Comment by lkurzyniec** [comment]
done. 
@Arasz please check is it ok or not. if not then let me know ;)

**Comment by Arasz** [comment]
Merged 👍
